# Generated by Django 4.1.7 on 2023-03-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=60)),
                ('endereco', models.CharField(max_length=80, null=True)),
                ('cidade', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
